[2022-04-24 14:48:34,338] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:48:34,354] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:48:34,355] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:48:34,355] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:48:34,355] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:48:34,376] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_ext_task> on 2000-01-01 00:00:00+00:00
[2022-04-24 14:48:34,384] {standard_task_runner.py:52} INFO - Started process 3335 to run task
[2022-04-24 14:48:34,395] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'roster_data_bq_dag', 'gcs_2_bq_ext_task', 'scheduled__2000-01-01T00:00:00+00:00', '--job-id', '2218', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp6nlu1_ff', '--error-file', '/tmp/tmpzp39xf12']
[2022-04-24 14:48:34,397] {standard_task_runner.py:77} INFO - Job 2218: Subtask gcs_2_bq_ext_task
[2022-04-24 14:48:34,498] {logging_mixin.py:109} INFO - Running <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2000-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:48:34,747] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=roster_data_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_ext_task
AIRFLOW_CTX_EXECUTION_DATE=2000-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2000-01-01T00:00:00+00:00
[2022-04-24 14:48:34,749] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:48:35,245] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-339113/datasets/nfl_project/tables?prettyPrint=false: Error while reading table: external_roster, error message: Failed to expand table external_roster with file pattern gs://nfl_data_lake_dtc-de-course-339113/raw/roster/2009/*.parquet: matched no files.
[2022-04-24 14:48:35,262] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=roster_data_bq_dag, task_id=gcs_2_bq_ext_task, execution_date=20000101T000000, start_date=20220424T144834, end_date=20220424T144835
[2022-04-24 14:48:35,275] {standard_task_runner.py:92} ERROR - Failed to execute job 2218 for task gcs_2_bq_ext_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-339113/datasets/nfl_project/tables?prettyPrint=false: Error while reading table: external_roster, error message: Failed to expand table external_roster with file pattern gs://nfl_data_lake_dtc-de-course-339113/raw/roster/2009/*.parquet: matched no files.
[2022-04-24 14:48:35,324] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-24 14:48:35,357] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-24 14:53:55,848] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:53:55,881] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:53:55,881] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:53:55,881] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:53:55,881] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:53:55,918] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_ext_task> on 2000-01-01 00:00:00+00:00
[2022-04-24 14:53:55,926] {standard_task_runner.py:52} INFO - Started process 4137 to run task
[2022-04-24 14:53:55,942] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'roster_data_bq_dag', 'gcs_2_bq_ext_task', 'scheduled__2000-01-01T00:00:00+00:00', '--job-id', '2263', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpy_s5myd6', '--error-file', '/tmp/tmpbv2bevxm']
[2022-04-24 14:53:55,946] {standard_task_runner.py:77} INFO - Job 2263: Subtask gcs_2_bq_ext_task
[2022-04-24 14:53:56,080] {logging_mixin.py:109} INFO - Running <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2000-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:53:56,200] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=roster_data_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_ext_task
AIRFLOW_CTX_EXECUTION_DATE=2000-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2000-01-01T00:00:00+00:00
[2022-04-24 14:53:56,202] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:53:56,968] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=roster_data_bq_dag, task_id=gcs_2_bq_ext_task, execution_date=20000101T000000, start_date=20220424T145355, end_date=20220424T145356
[2022-04-24 14:53:57,013] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-24 14:53:57,066] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 13:18:49,505] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 13:18:49,577] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2000-01-01T00:00:00+00:00 [queued]>
[2022-04-25 13:18:49,577] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 13:18:49,578] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 13:18:49,579] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 13:18:49,647] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_ext_task> on 2000-01-01 00:00:00+00:00
[2022-04-25 13:18:49,671] {standard_task_runner.py:52} INFO - Started process 5520 to run task
[2022-04-25 13:18:49,700] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'roster_data_bq_dag', 'gcs_2_bq_ext_task', 'scheduled__2000-01-01T00:00:00+00:00', '--job-id', '2431', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp9z5xejd5', '--error-file', '/tmp/tmprsqa92ta']
[2022-04-25 13:18:49,708] {standard_task_runner.py:77} INFO - Job 2431: Subtask gcs_2_bq_ext_task
[2022-04-25 13:18:49,947] {logging_mixin.py:109} INFO - Running <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2000-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 13:18:50,371] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=roster_data_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_ext_task
AIRFLOW_CTX_EXECUTION_DATE=2000-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2000-01-01T00:00:00+00:00
[2022-04-25 13:18:50,378] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 13:18:51,149] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=roster_data_bq_dag, task_id=gcs_2_bq_ext_task, execution_date=20000101T000000, start_date=20220425T131849, end_date=20220425T131851
[2022-04-25 13:18:51,323] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 13:18:51,382] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
