[2022-04-24 14:46:06,613] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:46:06,629] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:46:06,629] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:46:06,629] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:46:06,629] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:46:06,648] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2003-01-01 00:00:00+00:00
[2022-04-24 14:46:06,659] {standard_task_runner.py:52} INFO - Started process 2835 to run task
[2022-04-24 14:46:06,677] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '2176', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp1ej6ah6i', '--error-file', '/tmp/tmpw6_4y2up']
[2022-04-24 14:46:06,685] {standard_task_runner.py:77} INFO - Job 2176: Subtask bq_ext_2_part_task
[2022-04-24 14:46:06,765] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:46:06,857] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-04-24 14:46:06,859] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:46:06,869] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-24 14:46:06,878] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2003_01_01T00_00_00_00_00_7024fe331a5d532397dd29cbe97eaf07
[2022-04-24 14:46:10,911] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20030101T000000, start_date=20220424T144606, end_date=20220424T144610
[2022-04-24 14:46:10,956] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-24 14:46:10,987] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:35:46,600] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:35:46,614] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:35:46,614] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:35:46,614] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:35:46,614] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:35:46,632] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2003-01-01 00:00:00+00:00
[2022-04-25 12:35:46,639] {standard_task_runner.py:52} INFO - Started process 588 to run task
[2022-04-25 12:35:46,649] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '2332', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpo0m4su5u', '--error-file', '/tmp/tmp6sqke0hz']
[2022-04-25 12:35:46,650] {standard_task_runner.py:77} INFO - Job 2332: Subtask bq_ext_2_part_task
[2022-04-25 12:35:46,742] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:35:46,816] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-04-25 12:35:46,818] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:35:46,824] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:35:46,834] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2003_01_01T00_00_00_00_00_391af1fa17095272e88c410190dcf6dd
[2022-04-25 12:35:52,208] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20030101T000000, start_date=20220425T123546, end_date=20220425T123552
[2022-04-25 12:35:52,229] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 12:35:52,269] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:42:43,625] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:42:43,654] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:42:43,654] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:42:43,654] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:42:43,654] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:42:43,685] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2003-01-01 00:00:00+00:00
[2022-04-25 12:42:43,695] {standard_task_runner.py:52} INFO - Started process 1563 to run task
[2022-04-25 12:42:43,710] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '2378', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp2de61erc', '--error-file', '/tmp/tmpdy8mxp7h']
[2022-04-25 12:42:43,712] {standard_task_runner.py:77} INFO - Job 2378: Subtask bq_ext_2_part_task
[2022-04-25 12:42:43,870] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:42:44,021] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-04-25 12:42:44,025] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:42:44,036] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:42:44,053] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2003_01_01T00_00_00_00_00_b8842f56e5f025f02c7ce9bf3b17d14a
[2022-04-25 12:42:48,118] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20030101T000000, start_date=20220425T124243, end_date=20220425T124248
[2022-04-25 12:42:48,184] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 12:42:48,228] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:44:01,946] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:44:01,968] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:44:01,968] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:44:01,968] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:44:01,969] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:44:01,984] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2003-01-01 00:00:00+00:00
[2022-04-25 12:44:01,996] {standard_task_runner.py:52} INFO - Started process 1814 to run task
[2022-04-25 12:44:02,003] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '2400', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpnapawj33', '--error-file', '/tmp/tmp2tu1knyb']
[2022-04-25 12:44:02,004] {standard_task_runner.py:77} INFO - Job 2400: Subtask bq_ext_2_part_task
[2022-04-25 12:44:02,094] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:44:02,166] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-04-25 12:44:02,169] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:44:02,178] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:44:02,186] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2003_01_01T00_00_00_00_00_832607c5c7102cf9f4d349ef7047648f
[2022-04-25 12:44:03,014] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_3_player_id' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2003_01_01T00_00_00_00_00_832607c5c7102cf9f4d349ef7047648f)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:44:03,037] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20030101T000000, start_date=20220425T124401, end_date=20220425T124403
[2022-04-25 12:44:03,059] {standard_task_runner.py:92} ERROR - Failed to execute job 2400 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_3_player_id' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2003_01_01T00_00_00_00_00_832607c5c7102cf9f4d349ef7047648f)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:44:03,079] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 12:44:03,108] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:58:24,116] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:58:24,132] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:58:24,132] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:58:24,132] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:58:24,132] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:58:24,144] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2003-01-01 00:00:00+00:00
[2022-04-25 12:58:24,150] {standard_task_runner.py:52} INFO - Started process 3395 to run task
[2022-04-25 12:58:24,159] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '2423', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp1v_dxsch', '--error-file', '/tmp/tmpnitv3uvj']
[2022-04-25 12:58:24,160] {standard_task_runner.py:77} INFO - Job 2423: Subtask bq_ext_2_part_task
[2022-04-25 12:58:24,226] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:58:24,299] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-04-25 12:58:24,301] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:58:24,312] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:58:24,332] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2003_01_01T00_00_00_00_00_5a5f0b9fc5d8a46d302a691c5ced5402
[2022-04-25 12:58:25,152] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_4_player_name' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2003_01_01T00_00_00_00_00_5a5f0b9fc5d8a46d302a691c5ced5402)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:58:25,170] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20030101T000000, start_date=20220425T125824, end_date=20220425T125825
[2022-04-25 12:58:25,183] {standard_task_runner.py:92} ERROR - Failed to execute job 2423 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_4_player_name' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2003_01_01T00_00_00_00_00_5a5f0b9fc5d8a46d302a691c5ced5402)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:58:25,214] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 12:58:25,255] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:58:25,283] {dagrun.py:530} ERROR - Marking run <DagRun pbp_data_bq_dag @ 2003-01-01 00:00:00+00:00: scheduled__2003-01-01T00:00:00+00:00, externally triggered: False> failed
[2022-04-25 12:58:25,283] {dagrun.py:605} INFO - DagRun Finished: dag_id=pbp_data_bq_dag, execution_date=2003-01-01 00:00:00+00:00, run_id=scheduled__2003-01-01T00:00:00+00:00, run_start_date=2022-04-25 12:58:19.244150+00:00, run_end_date=2022-04-25 12:58:25.283626+00:00, run_duration=6.039476, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2003-01-01 00:00:00+00:00, data_interval_end=2004-01-01 00:00:00+00:00, dag_hash=3bdd33d9fd043ad12f3a60cb8a1e21c6
