[2022-04-24 14:49:33,392] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data_bq_dag.gcs_2_bq_ext_task scheduled__2008-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:49:33,425] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data_bq_dag.gcs_2_bq_ext_task scheduled__2008-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:49:33,425] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:49:33,425] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:49:33,425] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:49:33,471] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_ext_task> on 2008-01-01 00:00:00+00:00
[2022-04-24 14:49:33,479] {standard_task_runner.py:52} INFO - Started process 3544 to run task
[2022-04-24 14:49:33,517] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'schedule_data_bq_dag', 'gcs_2_bq_ext_task', 'scheduled__2008-01-01T00:00:00+00:00', '--job-id', '2234', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpzfhycdom', '--error-file', '/tmp/tmpjv4g4njf']
[2022-04-24 14:49:33,518] {standard_task_runner.py:77} INFO - Job 2234: Subtask gcs_2_bq_ext_task
[2022-04-24 14:49:33,665] {logging_mixin.py:109} INFO - Running <TaskInstance: schedule_data_bq_dag.gcs_2_bq_ext_task scheduled__2008-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:49:33,800] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=schedule_data_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_ext_task
AIRFLOW_CTX_EXECUTION_DATE=2008-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2008-01-01T00:00:00+00:00
[2022-04-24 14:49:33,802] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:49:34,217] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-339113/datasets/nfl_project/tables?prettyPrint=false: Error while reading table: external_schedule, error message: Failed to expand table external_schedule with file pattern gs://nfl_data_lake_dtc-de-course-339113/raw/schedule/2009/*.parquet: matched no files.
[2022-04-24 14:49:34,244] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=schedule_data_bq_dag, task_id=gcs_2_bq_ext_task, execution_date=20080101T000000, start_date=20220424T144933, end_date=20220424T144934
[2022-04-24 14:49:34,267] {standard_task_runner.py:92} ERROR - Failed to execute job 2234 for task gcs_2_bq_ext_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-339113/datasets/nfl_project/tables?prettyPrint=false: Error while reading table: external_schedule, error message: Failed to expand table external_schedule with file pattern gs://nfl_data_lake_dtc-de-course-339113/raw/schedule/2009/*.parquet: matched no files.
[2022-04-24 14:49:34,311] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-24 14:49:34,417] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-24 14:54:12,064] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data_bq_dag.gcs_2_bq_ext_task scheduled__2008-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:54:12,079] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data_bq_dag.gcs_2_bq_ext_task scheduled__2008-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:54:12,080] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:54:12,080] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:54:12,080] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:54:12,100] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_ext_task> on 2008-01-01 00:00:00+00:00
[2022-04-24 14:54:12,108] {standard_task_runner.py:52} INFO - Started process 4230 to run task
[2022-04-24 14:54:12,114] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'schedule_data_bq_dag', 'gcs_2_bq_ext_task', 'scheduled__2008-01-01T00:00:00+00:00', '--job-id', '2274', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp37z5hf6z', '--error-file', '/tmp/tmpu6wuyhr7']
[2022-04-24 14:54:12,115] {standard_task_runner.py:77} INFO - Job 2274: Subtask gcs_2_bq_ext_task
[2022-04-24 14:54:12,199] {logging_mixin.py:109} INFO - Running <TaskInstance: schedule_data_bq_dag.gcs_2_bq_ext_task scheduled__2008-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:54:12,285] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=schedule_data_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_ext_task
AIRFLOW_CTX_EXECUTION_DATE=2008-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2008-01-01T00:00:00+00:00
[2022-04-24 14:54:12,288] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:54:12,887] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=schedule_data_bq_dag, task_id=gcs_2_bq_ext_task, execution_date=20080101T000000, start_date=20220424T145412, end_date=20220424T145412
[2022-04-24 14:54:12,927] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-24 14:54:12,961] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 13:19:21,432] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data_bq_dag.gcs_2_bq_ext_task scheduled__2008-01-01T00:00:00+00:00 [queued]>
[2022-04-25 13:19:21,463] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data_bq_dag.gcs_2_bq_ext_task scheduled__2008-01-01T00:00:00+00:00 [queued]>
[2022-04-25 13:19:21,463] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 13:19:21,464] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 13:19:21,464] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 13:19:21,503] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_ext_task> on 2008-01-01 00:00:00+00:00
[2022-04-25 13:19:21,511] {standard_task_runner.py:52} INFO - Started process 5748 to run task
[2022-04-25 13:19:21,529] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'schedule_data_bq_dag', 'gcs_2_bq_ext_task', 'scheduled__2008-01-01T00:00:00+00:00', '--job-id', '2466', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp7adls5vy', '--error-file', '/tmp/tmp1n871373']
[2022-04-25 13:19:21,535] {standard_task_runner.py:77} INFO - Job 2466: Subtask gcs_2_bq_ext_task
[2022-04-25 13:19:21,680] {logging_mixin.py:109} INFO - Running <TaskInstance: schedule_data_bq_dag.gcs_2_bq_ext_task scheduled__2008-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 13:19:21,819] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=schedule_data_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_ext_task
AIRFLOW_CTX_EXECUTION_DATE=2008-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2008-01-01T00:00:00+00:00
[2022-04-25 13:19:21,821] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 13:19:22,490] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=schedule_data_bq_dag, task_id=gcs_2_bq_ext_task, execution_date=20080101T000000, start_date=20220425T131921, end_date=20220425T131922
[2022-04-25 13:19:22,523] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 13:19:22,556] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
