[2022-04-24 14:49:33,366] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2009-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:49:33,383] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2009-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:49:33,383] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:49:33,384] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:49:33,384] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:49:33,404] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_ext_task> on 2009-01-01 00:00:00+00:00
[2022-04-24 14:49:33,414] {standard_task_runner.py:52} INFO - Started process 3543 to run task
[2022-04-24 14:49:33,435] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'roster_data_bq_dag', 'gcs_2_bq_ext_task', 'scheduled__2009-01-01T00:00:00+00:00', '--job-id', '2233', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpymqh9nf7', '--error-file', '/tmp/tmpy80ehzml']
[2022-04-24 14:49:33,440] {standard_task_runner.py:77} INFO - Job 2233: Subtask gcs_2_bq_ext_task
[2022-04-24 14:49:33,592] {logging_mixin.py:109} INFO - Running <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2009-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:49:33,771] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=roster_data_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_ext_task
AIRFLOW_CTX_EXECUTION_DATE=2009-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2009-01-01T00:00:00+00:00
[2022-04-24 14:49:33,773] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:49:34,187] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-339113/datasets/nfl_project/tables?prettyPrint=false: Error while reading table: external_roster, error message: Failed to expand table external_roster with file pattern gs://nfl_data_lake_dtc-de-course-339113/raw/roster/2009/*.parquet: matched no files.
[2022-04-24 14:49:34,210] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=roster_data_bq_dag, task_id=gcs_2_bq_ext_task, execution_date=20090101T000000, start_date=20220424T144933, end_date=20220424T144934
[2022-04-24 14:49:34,230] {standard_task_runner.py:92} ERROR - Failed to execute job 2233 for task gcs_2_bq_ext_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-339113/datasets/nfl_project/tables?prettyPrint=false: Error while reading table: external_roster, error message: Failed to expand table external_roster with file pattern gs://nfl_data_lake_dtc-de-course-339113/raw/roster/2009/*.parquet: matched no files.
[2022-04-24 14:49:34,286] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-24 14:49:34,337] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-24 14:55:30,478] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2009-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:55:30,493] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2009-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:55:30,494] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:55:30,494] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:55:30,494] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:55:30,518] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_ext_task> on 2009-01-01 00:00:00+00:00
[2022-04-24 14:55:30,531] {standard_task_runner.py:52} INFO - Started process 4485 to run task
[2022-04-24 14:55:30,541] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'roster_data_bq_dag', 'gcs_2_bq_ext_task', 'scheduled__2009-01-01T00:00:00+00:00', '--job-id', '2296', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpfk3jf366', '--error-file', '/tmp/tmpyk3jy6nw']
[2022-04-24 14:55:30,542] {standard_task_runner.py:77} INFO - Job 2296: Subtask gcs_2_bq_ext_task
[2022-04-24 14:55:30,667] {logging_mixin.py:109} INFO - Running <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2009-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:55:30,752] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=roster_data_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_ext_task
AIRFLOW_CTX_EXECUTION_DATE=2009-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2009-01-01T00:00:00+00:00
[2022-04-24 14:55:30,754] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:55:31,347] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=roster_data_bq_dag, task_id=gcs_2_bq_ext_task, execution_date=20090101T000000, start_date=20220424T145530, end_date=20220424T145531
[2022-04-24 14:55:31,394] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-24 14:55:31,428] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 13:19:20,429] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2009-01-01T00:00:00+00:00 [queued]>
[2022-04-25 13:19:20,461] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2009-01-01T00:00:00+00:00 [queued]>
[2022-04-25 13:19:20,462] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 13:19:20,462] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 13:19:20,462] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 13:19:20,497] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_2_bq_ext_task> on 2009-01-01 00:00:00+00:00
[2022-04-25 13:19:20,504] {standard_task_runner.py:52} INFO - Started process 5746 to run task
[2022-04-25 13:19:20,533] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'roster_data_bq_dag', 'gcs_2_bq_ext_task', 'scheduled__2009-01-01T00:00:00+00:00', '--job-id', '2464', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpgsoz4mrg', '--error-file', '/tmp/tmprdtv0kkv']
[2022-04-25 13:19:20,534] {standard_task_runner.py:77} INFO - Job 2464: Subtask gcs_2_bq_ext_task
[2022-04-25 13:19:20,726] {logging_mixin.py:109} INFO - Running <TaskInstance: roster_data_bq_dag.gcs_2_bq_ext_task scheduled__2009-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 13:19:20,923] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=roster_data_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_2_bq_ext_task
AIRFLOW_CTX_EXECUTION_DATE=2009-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2009-01-01T00:00:00+00:00
[2022-04-25 13:19:20,928] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 13:19:21,718] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=roster_data_bq_dag, task_id=gcs_2_bq_ext_task, execution_date=20090101T000000, start_date=20220425T131920, end_date=20220425T131921
[2022-04-25 13:19:21,799] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 13:19:21,881] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
