[2022-04-24 14:46:06,723] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:46:06,740] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:46:06,741] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:46:06,741] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:46:06,741] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:46:06,760] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2004-01-01 00:00:00+00:00
[2022-04-24 14:46:06,768] {standard_task_runner.py:52} INFO - Started process 2836 to run task
[2022-04-24 14:46:06,774] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '2177', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpxh2glbhu', '--error-file', '/tmp/tmpa_y68zcd']
[2022-04-24 14:46:06,776] {standard_task_runner.py:77} INFO - Job 2177: Subtask bq_ext_2_part_task
[2022-04-24 14:46:06,862] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:46:06,949] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-04-24 14:46:06,952] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:46:06,958] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-24 14:46:06,965] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2004_01_01T00_00_00_00_00_bc72a920396be88037d7c8d3c5a1c87f
[2022-04-24 14:46:11,011] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20040101T000000, start_date=20220424T144606, end_date=20220424T144611
[2022-04-24 14:46:11,049] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-24 14:46:11,080] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:35:46,607] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:35:46,622] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:35:46,622] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:35:46,623] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:35:46,623] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:35:46,641] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2004-01-01 00:00:00+00:00
[2022-04-25 12:35:46,651] {standard_task_runner.py:52} INFO - Started process 589 to run task
[2022-04-25 12:35:46,663] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '2333', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp70d1gesy', '--error-file', '/tmp/tmpmr5qiclf']
[2022-04-25 12:35:46,664] {standard_task_runner.py:77} INFO - Job 2333: Subtask bq_ext_2_part_task
[2022-04-25 12:35:46,760] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:35:46,853] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-04-25 12:35:46,855] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:35:46,861] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:35:46,869] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2004_01_01T00_00_00_00_00_6a71eddb3b10f8d52420e7e2caf3067b
[2022-04-25 12:35:51,605] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20040101T000000, start_date=20220425T123546, end_date=20220425T123551
[2022-04-25 12:35:51,696] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 12:35:51,742] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:42:43,618] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:42:43,649] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:42:43,655] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:42:43,659] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:42:43,659] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:42:43,688] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2004-01-01 00:00:00+00:00
[2022-04-25 12:42:43,697] {standard_task_runner.py:52} INFO - Started process 1564 to run task
[2022-04-25 12:42:43,707] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '2377', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpi566fkm2', '--error-file', '/tmp/tmp9uz0hdtv']
[2022-04-25 12:42:43,708] {standard_task_runner.py:77} INFO - Job 2377: Subtask bq_ext_2_part_task
[2022-04-25 12:42:43,840] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:42:44,020] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-04-25 12:42:44,022] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:42:44,036] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:42:44,064] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2004_01_01T00_00_00_00_00_fa4bb8f4c09721683d9355d98c9d5269
[2022-04-25 12:42:48,407] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20040101T000000, start_date=20220425T124243, end_date=20220425T124248
[2022-04-25 12:42:48,435] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 12:42:48,466] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:44:01,865] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:44:01,904] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:44:01,904] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:44:01,904] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:44:01,904] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:44:01,919] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2004-01-01 00:00:00+00:00
[2022-04-25 12:44:01,930] {standard_task_runner.py:52} INFO - Started process 1813 to run task
[2022-04-25 12:44:01,935] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '2399', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpqakae9in', '--error-file', '/tmp/tmpo8q0jidh']
[2022-04-25 12:44:01,936] {standard_task_runner.py:77} INFO - Job 2399: Subtask bq_ext_2_part_task
[2022-04-25 12:44:02,020] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:44:02,095] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-04-25 12:44:02,097] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:44:02,108] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:44:02,119] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2004_01_01T00_00_00_00_00_f2de23aaeeaac8e0ff528d53f5e88a27
[2022-04-25 12:44:02,938] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'tackle_for_loss_2_player_id' has type BYTE_ARRAY which does not match the target cpp_type DOUBLE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2004_01_01T00_00_00_00_00_f2de23aaeeaac8e0ff528d53f5e88a27)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:44:02,956] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20040101T000000, start_date=20220425T124401, end_date=20220425T124402
[2022-04-25 12:44:02,969] {standard_task_runner.py:92} ERROR - Failed to execute job 2399 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'tackle_for_loss_2_player_id' has type BYTE_ARRAY which does not match the target cpp_type DOUBLE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2004_01_01T00_00_00_00_00_f2de23aaeeaac8e0ff528d53f5e88a27)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:44:03,000] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 12:44:03,040] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:58:24,085] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:58:24,099] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:58:24,100] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:58:24,100] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:58:24,100] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:58:24,115] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2004-01-01 00:00:00+00:00
[2022-04-25 12:58:24,122] {standard_task_runner.py:52} INFO - Started process 3394 to run task
[2022-04-25 12:58:24,134] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '2422', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpk77_uz8z', '--error-file', '/tmp/tmpwq7wac4f']
[2022-04-25 12:58:24,135] {standard_task_runner.py:77} INFO - Job 2422: Subtask bq_ext_2_part_task
[2022-04-25 12:58:24,215] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:58:24,292] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-04-25 12:58:24,294] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:58:24,306] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:58:24,321] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2004_01_01T00_00_00_00_00_343c78acbb48f559b0db0a394bb1b242
[2022-04-25 12:58:25,185] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_4_player_id' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2004_01_01T00_00_00_00_00_343c78acbb48f559b0db0a394bb1b242)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:58:25,204] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20040101T000000, start_date=20220425T125824, end_date=20220425T125825
[2022-04-25 12:58:25,217] {standard_task_runner.py:92} ERROR - Failed to execute job 2422 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_4_player_id' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2004_01_01T00_00_00_00_00_343c78acbb48f559b0db0a394bb1b242)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:58:25,270] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 12:58:25,315] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:58:25,344] {dagrun.py:530} ERROR - Marking run <DagRun pbp_data_bq_dag @ 2004-01-01 00:00:00+00:00: scheduled__2004-01-01T00:00:00+00:00, externally triggered: False> failed
[2022-04-25 12:58:25,344] {dagrun.py:605} INFO - DagRun Finished: dag_id=pbp_data_bq_dag, execution_date=2004-01-01 00:00:00+00:00, run_id=scheduled__2004-01-01T00:00:00+00:00, run_start_date=2022-04-25 12:58:19.347523+00:00, run_end_date=2022-04-25 12:58:25.344681+00:00, run_duration=5.997158, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2004-01-01 00:00:00+00:00, data_interval_end=2005-01-01 00:00:00+00:00, dag_hash=3bdd33d9fd043ad12f3a60cb8a1e21c6
