[2022-04-24 14:46:55,274] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2010-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:46:55,285] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2010-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:46:55,285] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:46:55,285] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:46:55,285] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:46:55,297] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2010-01-01 00:00:00+00:00
[2022-04-24 14:46:55,304] {standard_task_runner.py:52} INFO - Started process 3012 to run task
[2022-04-24 14:46:55,310] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2010-01-01T00:00:00+00:00', '--job-id', '2190', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp33dka_rf', '--error-file', '/tmp/tmpkunzdiok']
[2022-04-24 14:46:55,312] {standard_task_runner.py:77} INFO - Job 2190: Subtask bq_ext_2_part_task
[2022-04-24 14:46:55,384] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2010-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:46:55,472] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2010-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2010-01-01T00:00:00+00:00
[2022-04-24 14:46:55,477] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:46:55,486] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-24 14:46:55,497] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2010_01_01T00_00_00_00_00_c38438f8406c3ad41534007d3cae6702
[2022-04-24 14:46:59,166] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20100101T000000, start_date=20220424T144655, end_date=20220424T144659
[2022-04-24 14:46:59,220] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-24 14:46:59,256] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:36:17,209] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2010-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:36:17,226] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2010-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:36:17,226] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:36:17,226] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:36:17,226] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:36:17,241] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2010-01-01 00:00:00+00:00
[2022-04-25 12:36:17,255] {standard_task_runner.py:52} INFO - Started process 717 to run task
[2022-04-25 12:36:17,269] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2010-01-01T00:00:00+00:00', '--job-id', '2344', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpn36qn_30', '--error-file', '/tmp/tmpce1isai5']
[2022-04-25 12:36:17,271] {standard_task_runner.py:77} INFO - Job 2344: Subtask bq_ext_2_part_task
[2022-04-25 12:36:17,419] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2010-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:36:17,509] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2010-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2010-01-01T00:00:00+00:00
[2022-04-25 12:36:17,511] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:36:17,521] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:36:17,536] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2010_01_01T00_00_00_00_00_828443bacd696bee0a27f663f99f861f
[2022-04-25 12:36:22,210] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20100101T000000, start_date=20220425T123617, end_date=20220425T123622
[2022-04-25 12:36:22,258] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 12:36:22,286] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:57:42,255] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2010-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:57:42,268] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2010-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:57:42,268] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:57:42,268] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:57:42,268] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:57:42,284] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2010-01-01 00:00:00+00:00
[2022-04-25 12:57:42,291] {standard_task_runner.py:52} INFO - Started process 3264 to run task
[2022-04-25 12:57:42,297] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2010-01-01T00:00:00+00:00', '--job-id', '2412', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpbp7ep5bj', '--error-file', '/tmp/tmpenzfwc0w']
[2022-04-25 12:57:42,298] {standard_task_runner.py:77} INFO - Job 2412: Subtask bq_ext_2_part_task
[2022-04-25 12:57:42,377] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2010-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:57:42,480] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2010-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2010-01-01T00:00:00+00:00
[2022-04-25 12:57:42,482] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:57:42,493] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:57:42,502] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2010_01_01T00_00_00_00_00_120dde7bcbd029b7baac7176a738b109
[2022-04-25 12:57:43,325] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_3_player_name' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2010_01_01T00_00_00_00_00_120dde7bcbd029b7baac7176a738b109)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:57:43,341] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20100101T000000, start_date=20220425T125742, end_date=20220425T125743
[2022-04-25 12:57:43,356] {standard_task_runner.py:92} ERROR - Failed to execute job 2412 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_3_player_name' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2010_01_01T00_00_00_00_00_120dde7bcbd029b7baac7176a738b109)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:57:43,399] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 12:57:43,459] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
