[2022-04-11 14:42:15,440] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data.download_data scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 14:42:15,451] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data.download_data scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 14:42:15,451] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:42:15,451] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-04-11 14:42:15,451] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:42:15,463] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): download_data> on 2019-01-01 00:00:00+00:00
[2022-04-11 14:42:15,471] {standard_task_runner.py:52} INFO - Started process 329957 to run task
[2022-04-11 14:42:15,478] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'schedule_data', 'download_data', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '1673', '--raw', '--subdir', 'DAGS_FOLDER/nfl_to_gcs.py', '--cfg-path', '/tmp/tmp_dq91qli', '--error-file', '/tmp/tmpx37j6o4x']
[2022-04-11 14:42:15,479] {standard_task_runner.py:77} INFO - Job 1673: Subtask download_data
[2022-04-11 14:42:15,541] {logging_mixin.py:109} INFO - Running <TaskInstance: schedule_data.download_data scheduled__2019-01-01T00:00:00+00:00 [running]> on host 4ed3eda454fd
[2022-04-11 14:42:15,590] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-11 14:42:15,613] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=schedule_data
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2022-04-11 14:42:15,614] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 29, in download_schedule_data
    schedule_data = pa.Table.from_pandas(nfl.load_schedule_data(year=year))
  File "/home/airflow/.local/lib/python3.7/site-packages/nflfastpy/__init__.py", line 89, in load_schedule_data
    raise TypeError('Please provide an integer between 1999 and 2021 for the year argument.')
TypeError: Please provide an integer between 1999 and 2021 for the year argument.
[2022-04-11 14:42:15,628] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=schedule_data, task_id=download_data, execution_date=20190101T000000, start_date=20220411T144215, end_date=20220411T144215
[2022-04-11 14:42:15,642] {standard_task_runner.py:92} ERROR - Failed to execute job 1673 for task download_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 29, in download_schedule_data
    schedule_data = pa.Table.from_pandas(nfl.load_schedule_data(year=year))
  File "/home/airflow/.local/lib/python3.7/site-packages/nflfastpy/__init__.py", line 89, in load_schedule_data
    raise TypeError('Please provide an integer between 1999 and 2021 for the year argument.')
TypeError: Please provide an integer between 1999 and 2021 for the year argument.
[2022-04-11 14:42:15,690] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-11 14:42:15,737] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
