[2022-04-11 17:11:43,893] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data.download_data scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 17:11:43,904] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data.download_data scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 17:11:43,905] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 17:11:43,905] {taskinstance.py:1239} INFO - Starting attempt 9 of 9
[2022-04-11 17:11:43,905] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 17:11:43,918] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): download_data> on 2019-01-01 00:00:00+00:00
[2022-04-11 17:11:43,926] {standard_task_runner.py:52} INFO - Started process 342283 to run task
[2022-04-11 17:11:43,931] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'schedule_data', 'download_data', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '1682', '--raw', '--subdir', 'DAGS_FOLDER/nfl_to_gcs.py', '--cfg-path', '/tmp/tmpo1ewqk9v', '--error-file', '/tmp/tmplcfdztib']
[2022-04-11 17:11:43,932] {standard_task_runner.py:77} INFO - Job 1682: Subtask download_data
[2022-04-11 17:11:43,996] {logging_mixin.py:109} INFO - Running <TaskInstance: schedule_data.download_data scheduled__2019-01-01T00:00:00+00:00 [running]> on host 4ed3eda454fd
[2022-04-11 17:11:44,060] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=schedule_data
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2022-04-11 17:11:44,068] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-11 17:11:44,069] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-04-11 17:11:44,070] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-04-11 17:11:44,071] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-04-11 17:11:44,072] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 17:11:44,072] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 17:11:44,073] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-04-11 17:11:44,074] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-04-11 17:11:44,075] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 17:11:44,076] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 17:11:44,077] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 17:11:44,078] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 17:11:44,413] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 30, in download_schedule_data
    pq.write_table(schedule_data,dest_file_template)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1986, in write_table
    **kwargs) as writer:
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 650, in __init__
    path, compression=None)
  File "pyarrow/_fs.pyx", line 670, in pyarrow._fs.FileSystem.open_output_stream
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file 'raw/schedule_data/2019/schedule_data2019.parquet'. Detail: [errno 2] No such file or directory
[2022-04-11 17:11:44,429] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=schedule_data, task_id=download_data, execution_date=20190101T000000, start_date=20220411T171143, end_date=20220411T171144
[2022-04-11 17:11:44,443] {standard_task_runner.py:92} ERROR - Failed to execute job 1682 for task download_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 30, in download_schedule_data
    pq.write_table(schedule_data,dest_file_template)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1986, in write_table
    **kwargs) as writer:
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 650, in __init__
    path, compression=None)
  File "pyarrow/_fs.pyx", line 670, in pyarrow._fs.FileSystem.open_output_stream
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file 'raw/schedule_data/2019/schedule_data2019.parquet'. Detail: [errno 2] No such file or directory
[2022-04-11 17:11:44,465] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-11 17:11:44,512] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
