[2022-04-11 17:19:03,336] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data.rm_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 17:19:03,370] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data.rm_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 17:19:03,370] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 17:19:03,370] {taskinstance.py:1239} INFO - Starting attempt 3 of 3
[2022-04-11 17:19:03,370] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 17:19:03,410] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): rm_task> on 2019-01-01 00:00:00+00:00
[2022-04-11 17:19:03,426] {standard_task_runner.py:52} INFO - Started process 342966 to run task
[2022-04-11 17:19:03,432] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'schedule_data', 'rm_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '1689', '--raw', '--subdir', 'DAGS_FOLDER/nfl_to_gcs.py', '--cfg-path', '/tmp/tmp2q9r4qml', '--error-file', '/tmp/tmp1iweh_8l']
[2022-04-11 17:19:03,433] {standard_task_runner.py:77} INFO - Job 1689: Subtask rm_task
[2022-04-11 17:19:03,506] {logging_mixin.py:109} INFO - Running <TaskInstance: schedule_data.rm_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 4ed3eda454fd
[2022-04-11 17:19:03,556] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-11 17:19:03,580] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=schedule_data
AIRFLOW_CTX_TASK_ID=rm_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2022-04-11 17:19:03,581] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-11 17:19:03,582] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm /opt/***/local_parquet_data2019.parquet']
[2022-04-11 17:19:03,598] {subprocess.py:85} INFO - Output:
[2022-04-11 17:19:03,603] {subprocess.py:89} INFO - rm: cannot remove '/opt/***/local_parquet_data2019.parquet': No such file or directory
[2022-04-11 17:19:03,603] {subprocess.py:93} INFO - Command exited with return code 1
[2022-04-11 17:19:03,620] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-04-11 17:19:03,627] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=schedule_data, task_id=rm_task, execution_date=20190101T000000, start_date=20220411T171903, end_date=20220411T171903
[2022-04-11 17:19:03,641] {standard_task_runner.py:92} ERROR - Failed to execute job 1689 for task rm_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-04-11 17:19:03,685] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-11 17:19:03,721] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-11 19:06:58,823] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data.rm_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 19:06:58,834] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: schedule_data.rm_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 19:06:58,835] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 19:06:58,835] {taskinstance.py:1239} INFO - Starting attempt 3 of 3
[2022-04-11 19:06:58,835] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 19:06:58,846] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): rm_task> on 2019-01-01 00:00:00+00:00
[2022-04-11 19:06:58,854] {standard_task_runner.py:52} INFO - Started process 352117 to run task
[2022-04-11 19:06:58,860] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'schedule_data', 'rm_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '1713', '--raw', '--subdir', 'DAGS_FOLDER/nfl_to_gcs.py', '--cfg-path', '/tmp/tmpy8_7djn4', '--error-file', '/tmp/tmp9qqhaspw']
[2022-04-11 19:06:58,862] {standard_task_runner.py:77} INFO - Job 1713: Subtask rm_task
[2022-04-11 19:06:58,925] {logging_mixin.py:109} INFO - Running <TaskInstance: schedule_data.rm_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 4ed3eda454fd
[2022-04-11 19:06:59,025] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=schedule_data
AIRFLOW_CTX_TASK_ID=rm_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2022-04-11 19:06:59,026] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-11 19:06:59,027] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo None']
[2022-04-11 19:06:59,044] {subprocess.py:85} INFO - Output:
[2022-04-11 19:06:59,047] {subprocess.py:89} INFO - None
[2022-04-11 19:06:59,047] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-11 19:06:59,075] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=schedule_data, task_id=rm_task, execution_date=20190101T000000, start_date=20220411T190658, end_date=20220411T190659
[2022-04-11 19:06:59,112] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 19:06:59,145] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
